const R=window.RECORD||{},$=s=>document.querySelector(s),app=$('#app');
const T={1:'Comparative Table',2:'JDK Installation',3:'Java Basics',4:'No task assigned',5:'No task assigned',6:'Classes, Objects & Nested Classes',7:'Strings & Inheritance',8:'Inheritance & Polymorphism',9:'Packages & Interfaces',10:'Exception Handling & Byte Streams',11:'Character Streams & Threads'};
const K=/(\/\/.*|"(?:\\.|[^"\\])*"|\b(?:public|class|static|void|int|double|float|long|char|byte|short|boolean|String|new|extends|implements|interface|package|import|if|else|for|while|return|final|try|catch|finally|throw|throws|super|this|true|false|null)\b|\b\d+(?:\.\d+)?[fFL]?\b)/g;
const H=c=>E(c).replace(K,m=>`<span class="${m[0]=='/'?'c':m[0]=='"'?'s':/\d/.test(m[0])?'n':'k'}">${m}</span>`);
const E=t=>{const d=document.createElement('div');d.textContent=t;return d.innerHTML};
$('#nav').innerHTML='<a href="#/"><b>⌂</b>Home</a>'+Object.keys(T).map(n=>`<a href="#/w/${n}"><b>${String(n).padStart(2,'0')}</b>Week ${n}</a>`).join('');
$('#menu').onclick=()=>$('#side').classList.toggle('open');$('#side').onclick=()=>$('#side').classList.remove('open');
$('#theme').onclick=()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme=='light'?'':'light'};
const total=()=>Object.values(R).reduce((a,w)=>a+(w.table?1:w.length),0);
function search(q){const l=q.toLowerCase(),r=[];Object.keys(R).forEach(n=>{const w=R[n];if(w.table){if(('week 1 comparative table java c python javascript '+q).length&&'comparative table java c c++ python javascript'.includes(l))r.push([n,0,'Comparative Table — Java, C, C++, Python & JavaScript'])}else w.forEach((p,i)=>{if((p.t+' '+(p.q||'')+' '+(p.code||'')).toLowerCase().includes(l))r.push([n,i+1,p.t])})});app.innerHTML=`<h1>Search</h1><p class="q">${r.length} result(s) for "${E(q)}"</p><div class="list">${r.map(([n,i,t],k)=>`<a style="--i:${k}" href="#/w/${n}${i?'/'+i:''}"><span class="num">W${n}${i?' · P'+i:''}</span><span>${E(t)}</span></a>`).join('')}</div>`}
$('#q').oninput=e=>{const v=e.target.value.trim();location.hash=v?'#/s/'+encodeURIComponent(v):'#/'};$('#q').onclick=e=>e.stopPropagation();
function home(){app.innerHTML=`<section class="profile"><img src="assets/profile.png" alt="Y. Vedavathi" onerror="this.outerHTML='<div class=ph>YV</div>'"><div><h1>Y. Vedavathi</h1><div class="info"><b>Roll No</b><span>25EU02132</span><b>Year</b><span>II Year</span><b>Branch</b><span>AI &amp; ML</span><b>Section</b><span>B</span><b>Subject</b><span>Java Programming</span></div></div></section><h2>Weekly Records <small style="opacity:.6;font-size:14px">(${total()} programs)</small></h2><div class="grid">${Object.keys(T).map(n=>`<a class="tile" style="--i:${n}" href="#/w/${n}">Week ${n}<small>${T[n]}</small></a>`).join('')}</div>`}
function week(n){const w=R[n];let h=`<p class="crumb"><a href="#/">Home</a> / Week ${n}</p><h1>Week ${n}: ${T[n]}</h1>`;
if(n==4||n==5)h+='<div class="empty">No programming task was assigned this week.</div>';
else if(!w)h+='<div class="empty">Content for this week is being added.</div>';
else if(w.table)h+=`<div class="wrap"><table><tr>${w.table[0].map(c=>`<th>${E(c)}</th>`).join('')}</tr>${w.table.slice(1).map(r=>`<tr>${r.map(c=>`<td>${E(c)}</td>`).join('')}</tr>`).join('')}</table></div>`;
else h+=`<div class="list">${w.map((p,i)=>`<a style="--i:${i}" href="#/w/${n}/${i+1}"><span class="num">P${i+1}</span><span>${E(p.t)}</span></a>`).join('')}</div>`;
app.innerHTML=h}
function prog(n,i){const w=R[n],p=w&&w[i-1];if(!p)return week(n);
const cn=((p.code||'').match(/public class (\w+)/)||(p.code||'').match(/class (\w+)/)||[0,'Main'])[1];let b=p.steps?`<ol>${p.steps.map(s=>`<li>${E(s)}</li>`).join('')}</ol>`:`<div class="term"><div class="bar"><i></i><i></i><i></i><span>${cn}.java</span></div><pre id="c">${H(p.code)}</pre></div><div class="term"><div class="bar"><i></i><i></i><i></i><span>Terminal — bash</span></div><pre class="out"><span class="p">$ javac ${cn}.java &amp;&amp; java ${cn}</span>${p.out.split('\n').map((l,k)=>`<span style="animation-delay:${.4+k*.18}s">${E(l)||' '}</span>`).join('')}<span style="animation-delay:${.6+p.out.split('\n').length*.18}s"><span class="p">$</span> <i class="cur"></i></span></pre></div><button class="cp" onclick="navigator.clipboard.writeText(document.getElementById('c').textContent)">Copy code</button>`;
app.innerHTML=`<p class="crumb"><a href="#/">Home</a> / <a href="#/w/${n}">Week ${n}</a> / Program ${i}</p><h1>Program ${i}: ${E(p.t)}</h1><p class="q">${E(p.q||'')}</p>${b}<div class="pn">${i>1?`<a class="btn" href="#/w/${n}/${i-1}">← Prev</a>`:'<span></span>'}${i<w.length?`<a class="btn" href="#/w/${n}/${i+1}">Next →</a>`:'<span></span>'}</div>`}
function route(){const [,k,n,i]=location.hash.split('/');document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('on',a.hash==='#/w/'+n||(!k&&a.hash==='#/')));
scrollTo(0,0);!k?home():k=='s'?search(decodeURIComponent(n||'')):i?prog(n,+i):week(n)}
addEventListener('hashchange',route);route();
